name: Build EXE with Pake

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Pake
        run: npm install -g pake-cli

      - name: Build App
        shell: cmd
        continue-on-error: true
        run: |
          pake ./jisuanqi.html ^
            --name "交易计算器" ^
            --use-local-file ^
            --keep-binary

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: 交易计算器-EXE
          path: C:\npm\prefix\node_modules\pake-cli\src-tauri\target\x86_64-pc-windows-msvc\release\pake-交易计算器.exe
